# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 12:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.IntegerField(primary_key=True, serialize=False)),
                ('billing_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.IntegerField(primary_key=True, serialize=False)),
                ('no_of_products', models.IntegerField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('contact_no', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MobileData',
            fields=[
                # ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(blank=True, db_column='Index', null=True)),
                ('display_size', models.TextField(blank=True, db_column='Display_Size', null=True)),
                ('internal_storage', models.TextField(blank=True, db_column='Internal_Storage', null=True)),
                ('model_name', models.TextField(blank=True, db_column='Model_Name', null=True)),
                ('model_number', models.TextField(blank=True, db_column='Model_Number', null=True)),
                ('primary_camera', models.TextField(blank=True, db_column='Primary_Camera', null=True)),
                ('processor_type', models.TextField(blank=True, db_column='Processor_Type', null=True)),
                ('ram', models.TextField(blank=True, db_column='RAM', null=True)),
                ('secondary_camera', models.TextField(blank=True, db_column='Secondary_Camera', null=True)),
                ('weight', models.TextField(blank=True, db_column='Weight', null=True)),
                ('image_urls', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'mobile_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_datetime', models.DateTimeField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pdt_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(max_length=45)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('units_in_stock', models.IntegerField()),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sup_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sup_name', models.CharField(blank=True, max_length=100, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('acc', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecom_webapp.Product')),
                ('model_no', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('spec', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'accessory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('pdt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecom_webapp.Product')),
                ('publisher', models.CharField(max_length=50)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('summary', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecom_webapp.Product')),
                ('gender', models.CharField(max_length=10)),
                ('material', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('size', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'clothes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecom_webapp.Product')),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('dimensions', models.CharField(blank=True, max_length=20, null=True)),
                ('material', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'furniture',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GenerateBill',
            fields=[
                ('bill_id_fk', models.ForeignKey(db_column='bill_id_fk', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecom_webapp.Bill')),
            ],
            options={
                'db_table': 'generate_bill',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('laptop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecom_webapp.Product')),
                ('model_no', models.CharField(blank=True, max_length=20, null=True)),
                ('display_size', models.CharField(blank=True, max_length=10, null=True)),
                ('harddisk_capacity', models.CharField(blank=True, max_length=10, null=True)),
                ('ram', models.CharField(blank=True, max_length=5, null=True)),
                ('processor', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'laptop',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mobiles',
            fields=[
                ('mobile', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecom_webapp.Product')),
                ('model_no', models.CharField(max_length=20)),
                ('ram', models.CharField(max_length=5)),
                ('screen_size', models.CharField(max_length=10)),
                ('internal_memory', models.CharField(max_length=10)),
                ('processor', models.CharField(max_length=50)),
                ('primary_camera', models.CharField(blank=True, max_length=5, null=True)),
                ('secondary_camera', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'mobiles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecom_webapp.Product')),
                ('image_url', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'product_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductsInCart',
            fields=[
                ('cart_id_fk', models.ForeignKey(db_column='cart_id_fk', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecom_webapp.Cart')),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'products_in_cart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductSupply',
            fields=[
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecom_webapp.Supplier')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'product_supply',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Television',
            fields=[
                ('tv', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecom_webapp.Product')),
                ('model_no', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('display_size', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'television',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='ecom_webapp.Books')),
                ('author_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'authors',
                'managed': False,
            },
        ),
    ]
