# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mobiledata',
            options={'managed': True},
        ),
    ]
