# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_webapp', '0004_auto_20171028_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='model_no',
            field=models.CharField(max_length=100),
        ),
    ]
