# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-28 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_webapp', '0006_auto_20171028_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobiles',
            name='primary_camera',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
