# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-30 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_webapp', '0009_auto_20171030_1917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bill',
            options={'managed': True},
        ),
    ]
