# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_webapp', '0012_auto_20171030_1936'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='laptop',
            options={'managed': True},
        ),
    ]
