# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_webapp', '0013_auto_20171031_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='processor',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
