# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 17:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_webapp', '0014_auto_20171031_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='furniture',
            options={'managed': True},
        ),
    ]
