# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-31 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom_webapp', '0015_auto_20171031_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='furniture',
            name='dimensions',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
